spring:
   kafka:           
      bootstrap-servers: kafka:29091
      group-id: precificador-ativo
   datasource:
      platform: postgres
      url: jdbc:postgresql://postgres:5432/agendamento
      username: developer
      password: development
   jpa:
      show-sql: true
      generate-ddl: false
      hibernate:
         ddl-auto: none